# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  displayName: Docker Image SHA
  name: getImageSha
  inputs:
    azureSubscription: 'wip_cmx_kev'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr repository list --name $(acrregistry)'
    addSpnToEnvironment: true
